version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    ports:
      - "5432:5432"
    networks:
      - rosatom-quizzes-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rosatom-quizzes-network

  rosatom-quizzes-bot:
    container_name: rosatom-quizzes-bot
    restart: always
    build:
      context: .
    networks:
      - rosatom-quizzes-network
    env_file:
      - ".env"
    volumes:
      - ./rosatom_quizzes_bot:/src/rosatom_quizzes_bot
      - ./migrations:/src/migrations
      - ./media:/src/media
      - ./logs:/src/logs
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

networks:
  rosatom-quizzes-network:
    driver: bridge